name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */24 * * *'

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main
      
      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: 'hshndpoonam'
          COUNT: 9
          STYLE: "blog-left"
          BLOG_URL: "https://hashnode.com/@hshndpoonam"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

